#!/usr/bin/env bash

psql --username=viewer shows -c 'SELECT * FROM users LIMIT 1;'
psql --username=viewer shows -c 'INSERT INTO users(user_id,registration_date,firstname,lastname,email,password) VALUES (666666666,"pouet",Lol,Nick,lol.nick@useless.com,pouet42);'

