DROP OWNED BY reader;
REVOKE ALL PRIVILEGES ON SCHEMA public FROM reader;
REVOKE ALL ON ALL TABLES IN SCHEMA public FROM reader;
REVOKE CONNECT ON DATABASE shows FROM reader;
REVOKE reader FROM viewer;
DROP ROLE viewer;
DROP ROLE reader;

CREATE ROLE reader;

GRANT USAGE ON SCHEMA public TO  reader;
GRANT SELECT ON ALL TABLES IN SCHEMA public TO reader;

ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT SELECT ON TABLES TO reader;

CREATE ROLE viewer LOGIN ENCRYPTED PASSWORD 'viewer42';
GRANT reader TO viewer;
